name: authentication_flow
description: A App to learn and master Firebase Authentication.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # IOs package
  cupertino_icons: ^1.0.2

  # BLoC for Flutter package
  bloc_flutter: ^0.1.0

  # Firebase packages
  firebase_core: ^1.14.1
  firebase_auth: ^3.3.14

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
